version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo "Installing dependencies..."
      - npm install
      - npm install -g create-react-app 
      - create-react-app employee
  build:
    commands:
      - echo "Building react project"
      - npm run build
  post_build:
    commands:
      - echo "Updating files in S3 bucket..."
      - aws s3 sync build/Dashboard/ s3://employee-app-bucket-pranjul --delete